#!/bin/sh

# Minimize the number of manually installed packages in the image

# Finds all packages which could be marked as automatically installed and marks
# them as such

set -e

chroot_directory=$1

auto_packages=$(./auto-markable-pkgs $chroot_directory)
if [ -n "$auto_packages" ]; then
	chroot $chroot_directory apt-mark auto $auto_packages
fi
[ -z "$(./auto-markable-pkgs $chroot_directory 2> /dev/null)" ]

